<a href="https://colab.research.google.com/github/CodeWith-Sana/Learn-ML-WithSana/blob/main/dealing_with_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd

In [41]:
# Set random seed for reproducibility
np.random.seed(42)

# Create a raw, messy dataset
data = {
    "Employee_ID": [
        "EMP01",
        "EMP02",
        "EMP03",
        "EMP04",
        "EMP01",
        "EMP05",
        "EMP06",
        "EMP07",
        "EMP08",
        "EMP09",
    ],
    "Age": [28, np.nan, 45, 33, 28, 52, "thirty-one", 41, 19, 62],
    "Join_Date": [
        "2023-01-15",
        "2022-11-05",
        "12/04/2021",
        "2024-02-18",
        "2023-01-15",
        np.nan,
        "2020-08-22",
        "2025-01-01",
        "2023-06-30",
        "invalid_date",
    ],
    "Salary": [
        55000,
        62000,
        85000,
        -4000,
        55000,
        110000,
        72000,
        np.nan,
        48000,
        95000,
    ],
    "Department": [
        "HR",
        "IT",
        "Fin",
        "Marketing",
        "HR",
        "IT",
        "Sales",
        "  HR  ",
        "Fin",
        "IT",
    ],
}

In [42]:
data

{'Employee_ID': ['EMP01',
  'EMP02',
  'EMP03',
  'EMP04',
  'EMP01',
  'EMP05',
  'EMP06',
  'EMP07',
  'EMP08',
  'EMP09'],
 'Age': [28, nan, 45, 33, 28, 52, 'thirty-one', 41, 19, 62],
 'Join_Date': ['2023-01-15',
  '2022-11-05',
  '12/04/2021',
  '2024-02-18',
  '2023-01-15',
  nan,
  '2020-08-22',
  '2025-01-01',
  '2023-06-30',
  'invalid_date'],
 'Salary': [55000,
  62000,
  85000,
  -4000,
  55000,
  110000,
  72000,
  nan,
  48000,
  95000],
 'Department': ['HR',
  'IT',
  'Fin',
  'Marketing',
  'HR',
  'IT',
  'Sales',
  '  HR  ',
  'Fin',
  'IT']}

AttributeError: 'dict' object has no attribute 'info'

to create a dataframe from data (dict)

In [43]:
df = pd.DataFrame(data)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     object
 1   Age          9 non-null      object
 2   Join_Date    9 non-null      object
 3   Salary       9 non-null      float64
 4   Department   10 non-null     object
dtypes: float64(1), object(4)
memory usage: 532.0+ bytes

In [44]:
df.head()

  Employee_ID  Age   Join_Date   Salary Department
0       EMP01   28  2023-01-15  55000.0         HR
1       EMP02  NaN  2022-11-05  62000.0         IT
2       EMP03   45  12/04/2021  85000.0        Fin
3       EMP04   33  2024-02-18  -4000.0  Marketing
4       EMP01   28  2023-01-15  55000.0         HR

In [10]:
#to insert new data or  row

# Create the new row as a mini DataFrame
new_row = pd.DataFrame([[np.nan, 0, "?", 65000, "IT"]], columns=df.columns)

# Insert at index position 0 (the very top)
df = pd.concat([new_row, df]).reset_index(drop=True)

In [45]:
df.tail()

  Employee_ID         Age     Join_Date    Salary Department
5       EMP05          52           NaN  110000.0         IT
6       EMP06  thirty-one    2020-08-22   72000.0      Sales
7       EMP07          41    2025-01-01       NaN       HR
8       EMP08          19    2023-06-30   48000.0        Fin
9       EMP09          62  invalid_date   95000.0         IT

In [12]:
df.head()

  Employee_ID  Age   Join_Date   Salary Department
0         NaN    0           ?  65000.0         IT
1       EMP01   28  2023-01-15  55000.0         HR
2       EMP02  NaN  2022-11-05  62000.0         IT
3       EMP03   45  12/04/2021  85000.0        Fin
4       EMP04   33  2024-02-18  -4000.0  Marketing

In [14]:
# Insert at the very end using the length of the dataframe
df.loc[len(df)] = ["EMP10", 35, "2026-03-01", "?", "IT"]

In [46]:
df

  Employee_ID         Age     Join_Date    Salary Department
0       EMP01          28    2023-01-15   55000.0         HR
1       EMP02         NaN    2022-11-05   62000.0         IT
2       EMP03          45    12/04/2021   85000.0        Fin
3       EMP04          33    2024-02-18   -4000.0  Marketing
4       EMP01          28    2023-01-15   55000.0         HR
5       EMP05          52           NaN  110000.0         IT
6       EMP06  thirty-one    2020-08-22   72000.0      Sales
7       EMP07          41    2025-01-01       NaN       HR
8       EMP08          19    2023-06-30   48000.0        Fin
9       EMP09          62  invalid_date   95000.0         IT

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     object
 1   Age          9 non-null      object
 2   Join_Date    9 non-null      object
 3   Salary       9 non-null      float64
 4   Department   10 non-null     object
dtypes: float64(1), object(4)
memory usage: 532.0+ bytes

In [21]:
from numpy._core.defchararray import count
df.isnull().sum()

Employee_ID    1
Age            1
Join_Date      1
Salary         1
Department     0
dtype: int64

In [48]:
df.replace(to_replace='?', value =np.nan,  inplace =True)

In [49]:
df

  Employee_ID         Age     Join_Date    Salary Department
0       EMP01          28    2023-01-15   55000.0         HR
1       EMP02         NaN    2022-11-05   62000.0         IT
2       EMP03          45    12/04/2021   85000.0        Fin
3       EMP04          33    2024-02-18   -4000.0  Marketing
4       EMP01          28    2023-01-15   55000.0         HR
5       EMP05          52           NaN  110000.0         IT
6       EMP06  thirty-one    2020-08-22   72000.0      Sales
7       EMP07          41    2025-01-01       NaN       HR
8       EMP08          19    2023-06-30   48000.0        Fin
9       EMP09          62  invalid_date   95000.0         IT

In [52]:
#replace null values in salary column with mean of that column
df['Salary'].replace(to_replace =np.nan , value = np.mean(df['Salary']) ,  inplace =True)

/tmp/ipykernel_387/2225145956.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].replace(to_replace =np.nan , value = np.mean(df['Salary']) ,  inplace =True)

In [53]:
df

  Employee_ID         Age     Join_Date         Salary Department
0       EMP01          28    2023-01-15   55000.000000         HR
1       EMP02         NaN    2022-11-05   62000.000000         IT
2       EMP03          45    12/04/2021   85000.000000        Fin
3       EMP04          33    2024-02-18   -4000.000000  Marketing
4       EMP01          28    2023-01-15   55000.000000         HR
5       EMP05          52           NaN  110000.000000         IT
6       EMP06  thirty-one    2020-08-22   72000.000000      Sales
7       EMP07          41    2025-01-01   64222.222222       HR
8       EMP08          19    2023-06-30   48000.000000        Fin
9       EMP09          62  invalid_date   95000.000000         IT

In [56]:
df['Join_Date'].replace(to_replace=[np.nan , "invalid_date"] , value= "0-0-0" , inplace = True)

/tmp/ipykernel_387/3230959956.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Join_Date'].replace(to_replace=[np.nan , "invalid_date"] , value= "0-0-0" , inplace = True)

In [57]:
df

  Employee_ID         Age   Join_Date         Salary Department
0       EMP01          28  2023-01-15   55000.000000         HR
1       EMP02         NaN  2022-11-05   62000.000000         IT
2       EMP03          45  12/04/2021   85000.000000        Fin
3       EMP04          33  2024-02-18   -4000.000000  Marketing
4       EMP01          28  2023-01-15   55000.000000         HR
5       EMP05          52       0-0-0  110000.000000         IT
6       EMP06  thirty-one  2020-08-22   72000.000000      Sales
7       EMP07          41  2025-01-01   64222.222222       HR
8       EMP08          19  2023-06-30   48000.000000        Fin
9       EMP09          62       0-0-0   95000.000000         IT

In [59]:
df['Age'].replace(to_replace="thirty-one" , value= 0, inplace = True)

/tmp/ipykernel_387/3600243646.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age'].replace(to_replace="thirty-one" , value= 0, inplace = True)

In [62]:
df['Age'].replace(to_replace=np.nan , value= np.mean(df['Age']) , inplace = True)

/tmp/ipykernel_387/3992389147.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].replace(to_replace=np.nan , value= np.mean(df['Age']) , inplace = True)

In [63]:
df

  Employee_ID        Age   Join_Date         Salary Department
0       EMP01  28.000000  2023-01-15   55000.000000         HR
1       EMP02  34.222222  2022-11-05   62000.000000         IT
2       EMP03  45.000000  12/04/2021   85000.000000        Fin
3       EMP04  33.000000  2024-02-18   -4000.000000  Marketing
4       EMP01  28.000000  2023-01-15   55000.000000         HR
5       EMP05  52.000000       0-0-0  110000.000000         IT
6       EMP06   0.000000  2020-08-22   72000.000000      Sales
7       EMP07  41.000000  2025-01-01   64222.222222       HR
8       EMP08  19.000000  2023-06-30   48000.000000        Fin
9       EMP09  62.000000       0-0-0   95000.000000         IT

In [64]:
#fill null values with custom values
df.fillna(value = {'Age' : df['Age'].mean() , 'Salary' : df['Salary'].median()})

  Employee_ID        Age   Join_Date         Salary Department
0       EMP01  28.000000  2023-01-15   55000.000000         HR
1       EMP02  34.222222  2022-11-05   62000.000000         IT
2       EMP03  45.000000  12/04/2021   85000.000000        Fin
3       EMP04  33.000000  2024-02-18   -4000.000000  Marketing
4       EMP01  28.000000  2023-01-15   55000.000000         HR
5       EMP05  52.000000       0-0-0  110000.000000         IT
6       EMP06   0.000000  2020-08-22   72000.000000      Sales
7       EMP07  41.000000  2025-01-01   64222.222222       HR
8       EMP08  19.000000  2023-06-30   48000.000000        Fin
9       EMP09  62.000000       0-0-0   95000.000000         IT

## Dealing With Catagorical Data

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data_url = 'http://vincentarelbundock.github.io/Rdatasets/csv/carData/Salaries.csv'
#with using index_col =0 will drop extra index column
df = pd.read_csv(data_url, index_col =0 )
df

              rank discipline  yrs.since.phd  yrs.service   sex  salary
rownames
1             Prof          B             19           18  Male  139750
2             Prof          B             20           16  Male  173200
3         AsstProf          B              4            3  Male   79750
4             Prof          B             45           39  Male  115000
5             Prof          B             40           41  Male  141500
...            ...        ...            ...          ...   ...     ...
393           Prof          A             33           30  Male  103106
394           Prof          A             31           19  Male  150564
395           Prof          A             42           25  Male  101738
396           Prof          A             25           15  Male   95329
397       AsstProf          A              8            4  Male   81035

[397 rows x 6 columns]

In [5]:
df_dummies = pd.get_dummies(df[['rank', 'sex']])
df_dummies

          rank_AssocProf  rank_AsstProf  rank_Prof  sex_Female  sex_Male
rownames
1                  False          False       True       False      True
2                  False          False       True       False      True
3                  False           True      False       False      True
4                  False          False       True       False      True
5                  False          False       True       False      True
...                  ...            ...        ...         ...       ...
393                False          False       True       False      True
394                False          False       True       False      True
395                False          False       True       False      True
396                False          False       True       False      True
397                False           True      False       False      True

[397 rows x 5 columns]

In [6]:
df_dummies = pd.get_dummies(df[['rank', 'sex']] , drop_first = True)
df_dummies

          rank_AsstProf  rank_Prof  sex_Male
rownames
1                 False       True      True
2                 False       True      True
3                  True      False      True
4                 False       True      True
5                 False       True      True
...                 ...        ...       ...
393               False       True      True
394               False       True      True
395               False       True      True
396               False       True      True
397                True      False      True

[397 rows x 3 columns]

In [8]:
df2_dummies = pd.get_dummies(df[['rank', 'sex' , 'discipline']] , drop_first = True )
df2_dummies

          rank_AsstProf  rank_Prof  sex_Male  discipline_B
rownames
1                 False       True      True          True
2                 False       True      True          True
3                  True      False      True          True
4                 False       True      True          True
5                 False       True      True          True
...                 ...        ...       ...           ...
393               False       True      True         False
394               False       True      True         False
395               False       True      True         False
396               False       True      True         False
397                True      False      True         False

[397 rows x 4 columns]

In [10]:
df3 = pd.concat([df2_dummies , df] , axis=1)
df3

          rank_AsstProf  rank_Prof  sex_Male  ...  yrs.service   sex  salary
rownames                                      ...
1                 False       True      True  ...           18  Male  139750
2                 False       True      True  ...           16  Male  173200
3                  True      False      True  ...            3  Male   79750
4                 False       True      True  ...           39  Male  115000
5                 False       True      True  ...           41  Male  141500
...                 ...        ...       ...  ...          ...   ...     ...
393               False       True      True  ...           30  Male  103106
394               False       True      True  ...           19  Male  150564
395               False       True      True  ...           25  Male  101738
396               False       True      True  ...           15  Male   95329
397                True      False      True  ...            4  Male   81035

[397 rows x 10 columns]

In [11]:
df3.drop(['rank' , 'sex', 'discipline'] , axis =1 , inplace =True)

In [12]:
df3

          rank_AsstProf  rank_Prof  ...  yrs.service  salary
rownames                            ...
1                 False       True  ...           18  139750
2                 False       True  ...           16  173200
3                  True      False  ...            3   79750
4                 False       True  ...           39  115000
5                 False       True  ...           41  141500
...                 ...        ...  ...          ...     ...
393               False       True  ...           30  103106
394               False       True  ...           19  150564
395               False       True  ...           25  101738
396               False       True  ...           15   95329
397                True      False  ...            4   81035

[397 rows x 7 columns]

In [13]:
x =  df3.drop('salary' , axis =1).values
y = df3['salary']

In [14]:
x

array([[False, True, True, True, 19, 18],
       [False, True, True, True, 20, 16],
       [True, False, True, True, 4, 3],
       ...,
       [False, True, True, False, 42, 25],
       [False, True, True, False, 25, 15],
       [True, False, True, False, 8, 4]], dtype=object)

In [15]:
y

rownames
1      139750
2      173200
3       79750
4      115000
5      141500
        ...
393    103106
394    150564
395    101738
396     95329
397     81035
Name: salary, Length: 397, dtype: int64

In [17]:
x_train , x_test , y_train , y_test = train_test_split(x ,y, test_size=0.2 , random_state =42)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
x_train
x_test

array([[-0.46320556,  0.71380936, -3.27730693, -1.06859342, -0.81141908,
        -1.37032067],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.11801127,
         0.00772828],
       [ 2.15886875, -1.40093427, -3.27730693, -1.06859342, -1.19868172,
        -0.91097102],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -1.04377666,
        -0.75785447],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.50527391,
         0.08428655],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.12122919,
        -1.29376239],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.96998908,
         1.23266068],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.66339689,
        -1.37032067],
       [-0.46320556, -1.40093427, -3.27730693,  0.93580962, -0.81141908,
        -0.60473792],
       [-0.46320556,  0.71380936, -3.27730693, -1.06859342,  0.42782138,
        -0.29850482],
       [-0.46320556,  0.71380936, -3.27730693,  0.93580962, -0.34670391,
         0.00772828],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  1.20234666,
         1.38577723],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.42782138,
         0.39051965],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.42415643,
        -1.21720412],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.81508402,
         1.00298585],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -1.12122919,
        -0.75785447],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  1.35725172,
         0.69675275],
       [ 2.15886875, -1.40093427, -3.27730693, -1.06859342, -1.12122919,
        -1.14064584],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  2.20922954,
         2.53415135],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.4310393 ,
        -1.06408757],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.81141908,
        -1.14064584],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.42782138,
         0.39051965],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  1.12489414,
         1.4623355 ],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.26925138,
         0.00772828],
       [-0.46320556, -1.40093427,  0.30512858, -1.06859342, -0.34670391,
        -0.60473792],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.65651402,
        -0.52817964],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.50849183,
        -1.29376239],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.4310393 ,
        -1.21720412],
       [-0.46320556,  0.71380936, -3.27730693, -1.06859342,  1.04744161,
         0.08428655],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.42415643,
        -0.52817964],
       [-0.46320556,  0.71380936, -3.27730693,  0.93580962, -0.42415643,
         0.00772828],
       [-0.46320556,  0.71380936, -3.27730693,  0.93580962, -0.34670391,
        -0.60473792],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.96998908,
         0.39051965],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.04055874,
         0.2374031 ],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.27291632,
         0.08428655],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.58272644,
         1.00298585],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  1.74451436,
         2.0748017 ],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.19179885,
         0.16084483],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.50160896,
        -0.14538827],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  2.59649218,
         2.993501  ],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.11434632,
        -0.75785447],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.50527391,
         0.08428655],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -0.65651402,
        -0.98752929],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.57906149,
        -0.68129619],
       [-0.46320556,  0.71380936, -3.27730693,  0.93580962,  1.04744161,
         0.62019448],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.42415643,
        -1.14064584],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.11434632,
         0.16084483],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  1.35725172,
         0.77331103],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  1.82196689,
         2.0748017 ],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.03689379,
         0.16084483],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.11434632,
         0.00772828],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -1.04377666,
        -0.68129619],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.50527391,
        -0.83441274],
       [ 2.15886875, -1.40093427, -3.27730693,  0.93580962, -0.96632413,
        -0.98752929],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.19179885,
        -1.06408757],
       [ 2.15886875, -1.40093427,  0.30512858, -1.06859342, -1.58594436,
        -1.37032067],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.8888716 ,
        -0.52817964],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.50160896,
        -0.52817964],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.34670391,
         0.08428655],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -1.27613425,
        -0.91097102],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.89253655,
         0.92642758],
       [ 2.15886875, -1.40093427,  0.30512858,  0.93580962, -1.19868172,
        -1.21720412],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.50527391,
         0.69675275],
       [ 2.15886875, -1.40093427,  0.30512858, -1.06859342, -1.4310393 ,
        -1.29376239],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  1.51215678,
         0.00772828],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.42782138,
         0.77331103],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -0.73396655,
        -0.52817964],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.81508402,
         0.92642758],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -0.73396655,
        -0.68129619],
       [-0.46320556, -1.40093427,  0.30512858, -1.06859342, -0.65651402,
        -0.75785447],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -1.27613425,
        -0.91097102],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  0.19546379,
        -0.22194654],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  0.35036885,
         0.2374031 ],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  1.27979919,
         1.30921895],
       [-0.46320556, -1.40093427,  0.30512858,  0.93580962, -0.73396655,
        -0.91097102],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342, -0.57906149,
        -0.60473792],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962, -0.73396655,
        -0.52817964],
       [-0.46320556, -1.40093427, -3.27730693, -1.06859342, -0.96632413,
        -0.75785447],
       [-0.46320556,  0.71380936,  0.30512858,  0.93580962,  1.74451436,
         1.61545205],
       [-0.46320556,  0.71380936,  0.30512858, -1.06859342,  1.12489414,
         0.39051965]])

###Feature Engineering

In [31]:
xx = np.arange(1 ,11)
xx =xx.reshape(-1 , 1)

In [32]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree = 1)
x_features = pf.fit_transform(xx)

In [33]:
x_features

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  5.],
       [ 1.,  6.],
       [ 1.,  7.],
       [ 1.,  8.],
       [ 1.,  9.],
       [ 1., 10.]])

In [35]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree = 3)
x_features = pf.fit_transform(xx)
x_features

array([[   1.,    1.,    1.,    1.],
       [   1.,    2.,    4.,    8.],
       [   1.,    3.,    9.,   27.],
       [   1.,    4.,   16.,   64.],
       [   1.,    5.,   25.,  125.],
       [   1.,    6.,   36.,  216.],
       [   1.,    7.,   49.,  343.],
       [   1.,    8.,   64.,  512.],
       [   1.,    9.,   81.,  729.],
       [   1.,   10.,  100., 1000.]])